# Generated by Django 4.2.7 on 2023-11-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AircraftNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tail_number", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("incoming", "Incoming"),
                            ("departing", "Departing"),
                            ("quickturn", "Quickturn"),
                            ("off_ramp", "Off-Ramp"),
                            ("standby", "Standby"),
                            ("maintenance", "Maintenance"),
                            ("overnight", "Overnight"),
                        ],
                        max_length=20,
                    ),
                ),
                ("service_time", models.DateTimeField()),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("hanger1", "Hanger 1"),
                            ("hanger2", "Hanger 2"),
                            ("hanger3", "Hanger 3"),
                            ("hanger4", "Hanger 4"),
                            ("storage_r1", "Storage R1"),
                            ("tie_down", "Tie-Down"),
                            ("gama", "Gama"),
                            ("off_ramp", "Off-Ramp"),
                            ("customs", "Customs"),
                            ("netjets", "NetJets"),
                        ],
                        max_length=30,
                    ),
                ),
                ("aircraft_model", models.CharField(max_length=50)),
                (
                    "eta",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Estimated Time of Arrival"
                    ),
                ),
                (
                    "etd",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Estimated Time of Departure",
                    ),
                ),
                ("passenger_count", models.IntegerField(blank=True, null=True)),
                (
                    "fuel_qty",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Fuel Quantity"
                    ),
                ),
                (
                    "fuel_format",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("lbs", "Pounds (LBs)"),
                            ("kgs", "Kilograms (KGs)"),
                            ("gallons", "Gallons (Gs)"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("jet_a_neg", "Jet-A Negative (Jet-)"),
                            ("jet_a_pos", "Jet-A Positive (Jet+)"),
                            ("avgas", "Avgas (Av)"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "lav_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("fwr", "Fwr"),
                            ("aft", "Aft"),
                            ("fwr_aft", "Fwr & Aft"),
                            ("completed", "Completed"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "lav_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full", "Full"),
                            ("dump", "Dump"),
                            ("rinse", "Rinse"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("lav_gallons", models.IntegerField(blank=True, null=True)),
                (
                    "water_service_status",
                    models.CharField(
                        blank=True,
                        choices=[("active", "Active"), ("completed", "Completed")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "gpu_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("stage", "Stage"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "catering_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "catering_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("pic", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "customer_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("based_tenant", "Based Tenant"),
                            ("signature_silver", "Signature Status Silver"),
                            ("signature_gold", "Signature Status Gold"),
                            ("signature_platinum", "Signature Status Platinum"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "oil_status",
                    models.CharField(
                        blank=True,
                        choices=[("none", "None"), ("required", "Required")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("oil_type", models.CharField(blank=True, max_length=50, null=True)),
                ("oil_qty", models.IntegerField(blank=True, null=True)),
                (
                    "ladder_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
