# Generated by Django 4.2.7 on 2023-12-03 08:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("fuel_notes", "0002_aircraftnote_vacuum_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aircraftnote",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
